package top.testcross.zuji.bean;

import top.testcross.zuji.bean.interfaces.Example;

import java.util.ArrayList;
import java.util.List;

public class BmImgExample implements Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public BmImgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImgIdIsNull() {
            addCriterion("img_id is null");
            return (Criteria) this;
        }

        public Criteria andImgIdIsNotNull() {
            addCriterion("img_id is not null");
            return (Criteria) this;
        }

        public Criteria andImgIdEqualTo(String value) {
            addCriterion("img_id =", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotEqualTo(String value) {
            addCriterion("img_id <>", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdGreaterThan(String value) {
            addCriterion("img_id >", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdGreaterThanOrEqualTo(String value) {
            addCriterion("img_id >=", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLessThan(String value) {
            addCriterion("img_id <", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLessThanOrEqualTo(String value) {
            addCriterion("img_id <=", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdLike(String value) {
            addCriterion("img_id like", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotLike(String value) {
            addCriterion("img_id not like", value, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdIn(List<String> values) {
            addCriterion("img_id in", values, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotIn(List<String> values) {
            addCriterion("img_id not in", values, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdBetween(String value1, String value2) {
            addCriterion("img_id between", value1, value2, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgIdNotBetween(String value1, String value2) {
            addCriterion("img_id not between", value1, value2, "imgId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdIsNull() {
            addCriterion("img_src_id is null");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdIsNotNull() {
            addCriterion("img_src_id is not null");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdEqualTo(String value) {
            addCriterion("img_src_id =", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdNotEqualTo(String value) {
            addCriterion("img_src_id <>", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdGreaterThan(String value) {
            addCriterion("img_src_id >", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdGreaterThanOrEqualTo(String value) {
            addCriterion("img_src_id >=", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdLessThan(String value) {
            addCriterion("img_src_id <", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdLessThanOrEqualTo(String value) {
            addCriterion("img_src_id <=", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdLike(String value) {
            addCriterion("img_src_id like", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdNotLike(String value) {
            addCriterion("img_src_id not like", value, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdIn(List<String> values) {
            addCriterion("img_src_id in", values, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdNotIn(List<String> values) {
            addCriterion("img_src_id not in", values, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdBetween(String value1, String value2) {
            addCriterion("img_src_id between", value1, value2, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcIdNotBetween(String value1, String value2) {
            addCriterion("img_src_id not between", value1, value2, "imgSrcId");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeIsNull() {
            addCriterion("img_src_type is null");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeIsNotNull() {
            addCriterion("img_src_type is not null");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeEqualTo(Byte value) {
            addCriterion("img_src_type =", value, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeNotEqualTo(Byte value) {
            addCriterion("img_src_type <>", value, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeGreaterThan(Byte value) {
            addCriterion("img_src_type >", value, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("img_src_type >=", value, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeLessThan(Byte value) {
            addCriterion("img_src_type <", value, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeLessThanOrEqualTo(Byte value) {
            addCriterion("img_src_type <=", value, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeIn(List<Byte> values) {
            addCriterion("img_src_type in", values, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeNotIn(List<Byte> values) {
            addCriterion("img_src_type not in", values, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeBetween(Byte value1, Byte value2) {
            addCriterion("img_src_type between", value1, value2, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgSrcTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("img_src_type not between", value1, value2, "imgSrcType");
            return (Criteria) this;
        }

        public Criteria andImgContIsNull() {
            addCriterion("img_cont is null");
            return (Criteria) this;
        }

        public Criteria andImgContIsNotNull() {
            addCriterion("img_cont is not null");
            return (Criteria) this;
        }

        public Criteria andImgContEqualTo(String value) {
            addCriterion("img_cont =", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContNotEqualTo(String value) {
            addCriterion("img_cont <>", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContGreaterThan(String value) {
            addCriterion("img_cont >", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContGreaterThanOrEqualTo(String value) {
            addCriterion("img_cont >=", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContLessThan(String value) {
            addCriterion("img_cont <", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContLessThanOrEqualTo(String value) {
            addCriterion("img_cont <=", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContLike(String value) {
            addCriterion("img_cont like", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContNotLike(String value) {
            addCriterion("img_cont not like", value, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContIn(List<String> values) {
            addCriterion("img_cont in", values, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContNotIn(List<String> values) {
            addCriterion("img_cont not in", values, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContBetween(String value1, String value2) {
            addCriterion("img_cont between", value1, value2, "imgCont");
            return (Criteria) this;
        }

        public Criteria andImgContNotBetween(String value1, String value2) {
            addCriterion("img_cont not between", value1, value2, "imgCont");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Boolean value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Boolean value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Boolean value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Boolean value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Boolean> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Boolean> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bm_img
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}