package top.testcross.zuji.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PamCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public PamCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCmtIdIsNull() {
            addCriterion("cmt_id is null");
            return (Criteria) this;
        }

        public Criteria andCmtIdIsNotNull() {
            addCriterion("cmt_id is not null");
            return (Criteria) this;
        }

        public Criteria andCmtIdEqualTo(String value) {
            addCriterion("cmt_id =", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdNotEqualTo(String value) {
            addCriterion("cmt_id <>", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdGreaterThan(String value) {
            addCriterion("cmt_id >", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_id >=", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdLessThan(String value) {
            addCriterion("cmt_id <", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdLessThanOrEqualTo(String value) {
            addCriterion("cmt_id <=", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdLike(String value) {
            addCriterion("cmt_id like", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdNotLike(String value) {
            addCriterion("cmt_id not like", value, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdIn(List<String> values) {
            addCriterion("cmt_id in", values, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdNotIn(List<String> values) {
            addCriterion("cmt_id not in", values, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdBetween(String value1, String value2) {
            addCriterion("cmt_id between", value1, value2, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtIdNotBetween(String value1, String value2) {
            addCriterion("cmt_id not between", value1, value2, "cmtId");
            return (Criteria) this;
        }

        public Criteria andCmtContIsNull() {
            addCriterion("cmt_cont is null");
            return (Criteria) this;
        }

        public Criteria andCmtContIsNotNull() {
            addCriterion("cmt_cont is not null");
            return (Criteria) this;
        }

        public Criteria andCmtContEqualTo(String value) {
            addCriterion("cmt_cont =", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContNotEqualTo(String value) {
            addCriterion("cmt_cont <>", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContGreaterThan(String value) {
            addCriterion("cmt_cont >", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_cont >=", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContLessThan(String value) {
            addCriterion("cmt_cont <", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContLessThanOrEqualTo(String value) {
            addCriterion("cmt_cont <=", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContLike(String value) {
            addCriterion("cmt_cont like", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContNotLike(String value) {
            addCriterion("cmt_cont not like", value, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContIn(List<String> values) {
            addCriterion("cmt_cont in", values, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContNotIn(List<String> values) {
            addCriterion("cmt_cont not in", values, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContBetween(String value1, String value2) {
            addCriterion("cmt_cont between", value1, value2, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andCmtContNotBetween(String value1, String value2) {
            addCriterion("cmt_cont not between", value1, value2, "cmtCont");
            return (Criteria) this;
        }

        public Criteria andPostIdIsNull() {
            addCriterion("post_id is null");
            return (Criteria) this;
        }

        public Criteria andPostIdIsNotNull() {
            addCriterion("post_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostIdEqualTo(String value) {
            addCriterion("post_id =", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotEqualTo(String value) {
            addCriterion("post_id <>", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThan(String value) {
            addCriterion("post_id >", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThanOrEqualTo(String value) {
            addCriterion("post_id >=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThan(String value) {
            addCriterion("post_id <", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThanOrEqualTo(String value) {
            addCriterion("post_id <=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLike(String value) {
            addCriterion("post_id like", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotLike(String value) {
            addCriterion("post_id not like", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdIn(List<String> values) {
            addCriterion("post_id in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotIn(List<String> values) {
            addCriterion("post_id not in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdBetween(String value1, String value2) {
            addCriterion("post_id between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotBetween(String value1, String value2) {
            addCriterion("post_id not between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdIsNull() {
            addCriterion("cmt_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdIsNotNull() {
            addCriterion("cmt_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdEqualTo(String value) {
            addCriterion("cmt_parent_id =", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdNotEqualTo(String value) {
            addCriterion("cmt_parent_id <>", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdGreaterThan(String value) {
            addCriterion("cmt_parent_id >", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_parent_id >=", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdLessThan(String value) {
            addCriterion("cmt_parent_id <", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdLessThanOrEqualTo(String value) {
            addCriterion("cmt_parent_id <=", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdLike(String value) {
            addCriterion("cmt_parent_id like", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdNotLike(String value) {
            addCriterion("cmt_parent_id not like", value, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdIn(List<String> values) {
            addCriterion("cmt_parent_id in", values, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdNotIn(List<String> values) {
            addCriterion("cmt_parent_id not in", values, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdBetween(String value1, String value2) {
            addCriterion("cmt_parent_id between", value1, value2, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andCmtParentIdNotBetween(String value1, String value2) {
            addCriterion("cmt_parent_id not between", value1, value2, "cmtParentId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCmtTypeIsNull() {
            addCriterion("cmt_type is null");
            return (Criteria) this;
        }

        public Criteria andCmtTypeIsNotNull() {
            addCriterion("cmt_type is not null");
            return (Criteria) this;
        }

        public Criteria andCmtTypeEqualTo(Byte value) {
            addCriterion("cmt_type =", value, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeNotEqualTo(Byte value) {
            addCriterion("cmt_type <>", value, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeGreaterThan(Byte value) {
            addCriterion("cmt_type >", value, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("cmt_type >=", value, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeLessThan(Byte value) {
            addCriterion("cmt_type <", value, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeLessThanOrEqualTo(Byte value) {
            addCriterion("cmt_type <=", value, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeIn(List<Byte> values) {
            addCriterion("cmt_type in", values, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeNotIn(List<Byte> values) {
            addCriterion("cmt_type not in", values, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeBetween(Byte value1, Byte value2) {
            addCriterion("cmt_type between", value1, value2, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("cmt_type not between", value1, value2, "cmtType");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdIsNull() {
            addCriterion("cmt_target_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdIsNotNull() {
            addCriterion("cmt_target_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdEqualTo(String value) {
            addCriterion("cmt_target_user_id =", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdNotEqualTo(String value) {
            addCriterion("cmt_target_user_id <>", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdGreaterThan(String value) {
            addCriterion("cmt_target_user_id >", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("cmt_target_user_id >=", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdLessThan(String value) {
            addCriterion("cmt_target_user_id <", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdLessThanOrEqualTo(String value) {
            addCriterion("cmt_target_user_id <=", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdLike(String value) {
            addCriterion("cmt_target_user_id like", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdNotLike(String value) {
            addCriterion("cmt_target_user_id not like", value, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdIn(List<String> values) {
            addCriterion("cmt_target_user_id in", values, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdNotIn(List<String> values) {
            addCriterion("cmt_target_user_id not in", values, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdBetween(String value1, String value2) {
            addCriterion("cmt_target_user_id between", value1, value2, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtTargetUserIdNotBetween(String value1, String value2) {
            addCriterion("cmt_target_user_id not between", value1, value2, "cmtTargetUserId");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeIsNull() {
            addCriterion("cmt_create_time is null");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeIsNotNull() {
            addCriterion("cmt_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeEqualTo(Date value) {
            addCriterion("cmt_create_time =", value, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeNotEqualTo(Date value) {
            addCriterion("cmt_create_time <>", value, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeGreaterThan(Date value) {
            addCriterion("cmt_create_time >", value, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cmt_create_time >=", value, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeLessThan(Date value) {
            addCriterion("cmt_create_time <", value, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cmt_create_time <=", value, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeIn(List<Date> values) {
            addCriterion("cmt_create_time in", values, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeNotIn(List<Date> values) {
            addCriterion("cmt_create_time not in", values, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeBetween(Date value1, Date value2) {
            addCriterion("cmt_create_time between", value1, value2, "cmtCreateTime");
            return (Criteria) this;
        }

        public Criteria andCmtCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cmt_create_time not between", value1, value2, "cmtCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pam_comment
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}