package top.testcross.zuji.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PmPostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public PmPostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostIdIsNull() {
            addCriterion("post_id is null");
            return (Criteria) this;
        }

        public Criteria andPostIdIsNotNull() {
            addCriterion("post_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostIdEqualTo(String value) {
            addCriterion("post_id =", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotEqualTo(String value) {
            addCriterion("post_id <>", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThan(String value) {
            addCriterion("post_id >", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThanOrEqualTo(String value) {
            addCriterion("post_id >=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThan(String value) {
            addCriterion("post_id <", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThanOrEqualTo(String value) {
            addCriterion("post_id <=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLike(String value) {
            addCriterion("post_id like", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotLike(String value) {
            addCriterion("post_id not like", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdIn(List<String> values) {
            addCriterion("post_id in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotIn(List<String> values) {
            addCriterion("post_id not in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdBetween(String value1, String value2) {
            addCriterion("post_id between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotBetween(String value1, String value2) {
            addCriterion("post_id not between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountIsNull() {
            addCriterion("post_like_count is null");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountIsNotNull() {
            addCriterion("post_like_count is not null");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountEqualTo(Integer value) {
            addCriterion("post_like_count =", value, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountNotEqualTo(Integer value) {
            addCriterion("post_like_count <>", value, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountGreaterThan(Integer value) {
            addCriterion("post_like_count >", value, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("post_like_count >=", value, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountLessThan(Integer value) {
            addCriterion("post_like_count <", value, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("post_like_count <=", value, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountIn(List<Integer> values) {
            addCriterion("post_like_count in", values, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountNotIn(List<Integer> values) {
            addCriterion("post_like_count not in", values, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("post_like_count between", value1, value2, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("post_like_count not between", value1, value2, "postLikeCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountIsNull() {
            addCriterion("post_fav_count is null");
            return (Criteria) this;
        }

        public Criteria andPostFavCountIsNotNull() {
            addCriterion("post_fav_count is not null");
            return (Criteria) this;
        }

        public Criteria andPostFavCountEqualTo(Integer value) {
            addCriterion("post_fav_count =", value, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountNotEqualTo(Integer value) {
            addCriterion("post_fav_count <>", value, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountGreaterThan(Integer value) {
            addCriterion("post_fav_count >", value, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("post_fav_count >=", value, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountLessThan(Integer value) {
            addCriterion("post_fav_count <", value, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountLessThanOrEqualTo(Integer value) {
            addCriterion("post_fav_count <=", value, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountIn(List<Integer> values) {
            addCriterion("post_fav_count in", values, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountNotIn(List<Integer> values) {
            addCriterion("post_fav_count not in", values, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountBetween(Integer value1, Integer value2) {
            addCriterion("post_fav_count between", value1, value2, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostFavCountNotBetween(Integer value1, Integer value2) {
            addCriterion("post_fav_count not between", value1, value2, "postFavCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountIsNull() {
            addCriterion("post_cmt_count is null");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountIsNotNull() {
            addCriterion("post_cmt_count is not null");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountEqualTo(Integer value) {
            addCriterion("post_cmt_count =", value, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountNotEqualTo(Integer value) {
            addCriterion("post_cmt_count <>", value, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountGreaterThan(Integer value) {
            addCriterion("post_cmt_count >", value, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("post_cmt_count >=", value, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountLessThan(Integer value) {
            addCriterion("post_cmt_count <", value, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountLessThanOrEqualTo(Integer value) {
            addCriterion("post_cmt_count <=", value, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountIn(List<Integer> values) {
            addCriterion("post_cmt_count in", values, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountNotIn(List<Integer> values) {
            addCriterion("post_cmt_count not in", values, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountBetween(Integer value1, Integer value2) {
            addCriterion("post_cmt_count between", value1, value2, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostCmtCountNotBetween(Integer value1, Integer value2) {
            addCriterion("post_cmt_count not between", value1, value2, "postCmtCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountIsNull() {
            addCriterion("post_img_count is null");
            return (Criteria) this;
        }

        public Criteria andPostImgCountIsNotNull() {
            addCriterion("post_img_count is not null");
            return (Criteria) this;
        }

        public Criteria andPostImgCountEqualTo(Integer value) {
            addCriterion("post_img_count =", value, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountNotEqualTo(Integer value) {
            addCriterion("post_img_count <>", value, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountGreaterThan(Integer value) {
            addCriterion("post_img_count >", value, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("post_img_count >=", value, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountLessThan(Integer value) {
            addCriterion("post_img_count <", value, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountLessThanOrEqualTo(Integer value) {
            addCriterion("post_img_count <=", value, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountIn(List<Integer> values) {
            addCriterion("post_img_count in", values, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountNotIn(List<Integer> values) {
            addCriterion("post_img_count not in", values, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountBetween(Integer value1, Integer value2) {
            addCriterion("post_img_count between", value1, value2, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostImgCountNotBetween(Integer value1, Integer value2) {
            addCriterion("post_img_count not between", value1, value2, "postImgCount");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdIsNull() {
            addCriterion("post_cp_img_id is null");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdIsNotNull() {
            addCriterion("post_cp_img_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdEqualTo(String value) {
            addCriterion("post_cp_img_id =", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdNotEqualTo(String value) {
            addCriterion("post_cp_img_id <>", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdGreaterThan(String value) {
            addCriterion("post_cp_img_id >", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdGreaterThanOrEqualTo(String value) {
            addCriterion("post_cp_img_id >=", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdLessThan(String value) {
            addCriterion("post_cp_img_id <", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdLessThanOrEqualTo(String value) {
            addCriterion("post_cp_img_id <=", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdLike(String value) {
            addCriterion("post_cp_img_id like", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdNotLike(String value) {
            addCriterion("post_cp_img_id not like", value, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdIn(List<String> values) {
            addCriterion("post_cp_img_id in", values, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdNotIn(List<String> values) {
            addCriterion("post_cp_img_id not in", values, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdBetween(String value1, String value2) {
            addCriterion("post_cp_img_id between", value1, value2, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostCpImgIdNotBetween(String value1, String value2) {
            addCriterion("post_cp_img_id not between", value1, value2, "postCpImgId");
            return (Criteria) this;
        }

        public Criteria andPostVisibleIsNull() {
            addCriterion("post_visible is null");
            return (Criteria) this;
        }

        public Criteria andPostVisibleIsNotNull() {
            addCriterion("post_visible is not null");
            return (Criteria) this;
        }

        public Criteria andPostVisibleEqualTo(Boolean value) {
            addCriterion("post_visible =", value, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleNotEqualTo(Boolean value) {
            addCriterion("post_visible <>", value, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleGreaterThan(Boolean value) {
            addCriterion("post_visible >", value, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("post_visible >=", value, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleLessThan(Boolean value) {
            addCriterion("post_visible <", value, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleLessThanOrEqualTo(Boolean value) {
            addCriterion("post_visible <=", value, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleIn(List<Boolean> values) {
            addCriterion("post_visible in", values, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleNotIn(List<Boolean> values) {
            addCriterion("post_visible not in", values, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleBetween(Boolean value1, Boolean value2) {
            addCriterion("post_visible between", value1, value2, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostVisibleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("post_visible not between", value1, value2, "postVisible");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdIsNull() {
            addCriterion("post_intro_comment_id is null");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdIsNotNull() {
            addCriterion("post_intro_comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdEqualTo(String value) {
            addCriterion("post_intro_comment_id =", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdNotEqualTo(String value) {
            addCriterion("post_intro_comment_id <>", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdGreaterThan(String value) {
            addCriterion("post_intro_comment_id >", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdGreaterThanOrEqualTo(String value) {
            addCriterion("post_intro_comment_id >=", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdLessThan(String value) {
            addCriterion("post_intro_comment_id <", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdLessThanOrEqualTo(String value) {
            addCriterion("post_intro_comment_id <=", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdLike(String value) {
            addCriterion("post_intro_comment_id like", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdNotLike(String value) {
            addCriterion("post_intro_comment_id not like", value, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdIn(List<String> values) {
            addCriterion("post_intro_comment_id in", values, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdNotIn(List<String> values) {
            addCriterion("post_intro_comment_id not in", values, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdBetween(String value1, String value2) {
            addCriterion("post_intro_comment_id between", value1, value2, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroCommentIdNotBetween(String value1, String value2) {
            addCriterion("post_intro_comment_id not between", value1, value2, "postIntroCommentId");
            return (Criteria) this;
        }

        public Criteria andPostIntroIsNull() {
            addCriterion("post_intro is null");
            return (Criteria) this;
        }

        public Criteria andPostIntroIsNotNull() {
            addCriterion("post_intro is not null");
            return (Criteria) this;
        }

        public Criteria andPostIntroEqualTo(String value) {
            addCriterion("post_intro =", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroNotEqualTo(String value) {
            addCriterion("post_intro <>", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroGreaterThan(String value) {
            addCriterion("post_intro >", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroGreaterThanOrEqualTo(String value) {
            addCriterion("post_intro >=", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroLessThan(String value) {
            addCriterion("post_intro <", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroLessThanOrEqualTo(String value) {
            addCriterion("post_intro <=", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroLike(String value) {
            addCriterion("post_intro like", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroNotLike(String value) {
            addCriterion("post_intro not like", value, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroIn(List<String> values) {
            addCriterion("post_intro in", values, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroNotIn(List<String> values) {
            addCriterion("post_intro not in", values, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroBetween(String value1, String value2) {
            addCriterion("post_intro between", value1, value2, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPostIntroNotBetween(String value1, String value2) {
            addCriterion("post_intro not between", value1, value2, "postIntro");
            return (Criteria) this;
        }

        public Criteria andPiIdIsNull() {
            addCriterion("pi_id is null");
            return (Criteria) this;
        }

        public Criteria andPiIdIsNotNull() {
            addCriterion("pi_id is not null");
            return (Criteria) this;
        }

        public Criteria andPiIdEqualTo(String value) {
            addCriterion("pi_id =", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdNotEqualTo(String value) {
            addCriterion("pi_id <>", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdGreaterThan(String value) {
            addCriterion("pi_id >", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdGreaterThanOrEqualTo(String value) {
            addCriterion("pi_id >=", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdLessThan(String value) {
            addCriterion("pi_id <", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdLessThanOrEqualTo(String value) {
            addCriterion("pi_id <=", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdLike(String value) {
            addCriterion("pi_id like", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdNotLike(String value) {
            addCriterion("pi_id not like", value, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdIn(List<String> values) {
            addCriterion("pi_id in", values, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdNotIn(List<String> values) {
            addCriterion("pi_id not in", values, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdBetween(String value1, String value2) {
            addCriterion("pi_id between", value1, value2, "piId");
            return (Criteria) this;
        }

        public Criteria andPiIdNotBetween(String value1, String value2) {
            addCriterion("pi_id not between", value1, value2, "piId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeIsNull() {
            addCriterion("post_create_time is null");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeIsNotNull() {
            addCriterion("post_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeEqualTo(Date value) {
            addCriterion("post_create_time =", value, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeNotEqualTo(Date value) {
            addCriterion("post_create_time <>", value, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeGreaterThan(Date value) {
            addCriterion("post_create_time >", value, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("post_create_time >=", value, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeLessThan(Date value) {
            addCriterion("post_create_time <", value, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("post_create_time <=", value, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeIn(List<Date> values) {
            addCriterion("post_create_time in", values, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeNotIn(List<Date> values) {
            addCriterion("post_create_time not in", values, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeBetween(Date value1, Date value2) {
            addCriterion("post_create_time between", value1, value2, "postCreateTime");
            return (Criteria) this;
        }

        public Criteria andPostCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("post_create_time not between", value1, value2, "postCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pm_post
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}