package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.BmImg;
import top.testcross.zuji.bean.BmImgExample;

public interface BmImgMapper extends  Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int countByExample(BmImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int deleteByExample(BmImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int insert(BmImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int insertSelective(BmImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    List<BmImg> selectByExample(BmImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    BmImg selectByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") BmImg record, @Param("example") BmImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByExample(@Param("record") BmImg record, @Param("example") BmImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(BmImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_img
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByPrimaryKey(BmImg record);
}