package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.BmMessage;
import top.testcross.zuji.bean.BmMessageExample;

public interface BmMessageMapper  extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int countByExample(BmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int deleteByExample(BmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int insert(BmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int insertSelective(BmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    List<BmMessage> selectByExample(BmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    BmMessage selectByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") BmMessage record, @Param("example") BmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int updateByExample(@Param("record") BmMessage record, @Param("example") BmMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(BmMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message
     *
     * @mbggenerated Wed Nov 18 15:54:47 GMT+08:00 2020
     */
    int updateByPrimaryKey(BmMessage record);
}