package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.BmMessageH;
import top.testcross.zuji.bean.BmMessageHExample;

public interface BmMessageHMapper  extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int countByExample(BmMessageHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int deleteByExample(BmMessageHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int insert(BmMessageH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int insertSelective(BmMessageH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    List<BmMessageH> selectByExample(BmMessageHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    BmMessageH selectByPrimaryKey(String msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") BmMessageH record, @Param("example") BmMessageHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByExample(@Param("record") BmMessageH record, @Param("example") BmMessageHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(BmMessageH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_message_h
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByPrimaryKey(BmMessageH record);
}