package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.BmPostMark;
import top.testcross.zuji.bean.BmPostMarkExample;

public interface BmPostMarkMapper extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int countByExample(BmPostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int deleteByExample(BmPostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String pmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int insert(BmPostMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int insertSelective(BmPostMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    List<BmPostMark> selectByExample(BmPostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    BmPostMark selectByPrimaryKey(String pmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") BmPostMark record, @Param("example") BmPostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int updateByExample(@Param("record") BmPostMark record, @Param("example") BmPostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(BmPostMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_post_mark
     *
     * @mbggenerated Sat Nov 14 17:58:02 GMT+08:00 2020
     */
    int updateByPrimaryKey(BmPostMark record);
}