package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.PamComment;
import top.testcross.zuji.bean.PamCommentExample;

public interface PamCommentMapper extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int countByExample(PamCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int deleteByExample(PamCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String cmtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int insert(PamComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int insertSelective(PamComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    List<PamComment> selectByExample(PamCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    PamComment selectByPrimaryKey(String cmtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") PamComment record, @Param("example") PamCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByExample(@Param("record") PamComment record, @Param("example") PamCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(PamComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_comment
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByPrimaryKey(PamComment record);
}