package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.PamLike;
import top.testcross.zuji.bean.PamLikeExample;

public interface PamLikeMapper extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int countByExample(PamLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int deleteByExample(PamLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int insert(PamLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int insertSelective(PamLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    List<PamLike> selectByExample(PamLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    PamLike selectByPrimaryKey(String likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") PamLike record, @Param("example") PamLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByExample(@Param("record") PamLike record, @Param("example") PamLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(PamLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pam_like
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByPrimaryKey(PamLike record);
}