package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.PmPost;
import top.testcross.zuji.bean.PmPostExample;

public interface PmPostMapper extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int countByExample(PmPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int deleteByExample(PmPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int insert(PmPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int insertSelective(PmPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    List<PmPost> selectByExample(PmPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    PmPost selectByPrimaryKey(String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") PmPost record, @Param("example") PmPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByExample(@Param("record") PmPost record, @Param("example") PmPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(PmPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_post
     *
     * @mbggenerated Sun Nov 15 12:07:48 GMT+08:00 2020
     */
    int updateByPrimaryKey(PmPost record);
}