package top.testcross.zuji.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.testcross.zuji.bean.UimUser;
import top.testcross.zuji.bean.UimUserExample;

public interface UimUserMapper extends Mapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int countByExample(UimUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int deleteByExample(UimUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int insert(UimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int insertSelective(UimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    List<UimUser> selectByExample(UimUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    UimUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") UimUser record, @Param("example") UimUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByExample(@Param("record") UimUser record, @Param("example") UimUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UimUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uim_user
     *
     * @mbggenerated Fri Nov 13 23:23:31 GMT+08:00 2020
     */
    int updateByPrimaryKey(UimUser record);
}