spring:
  profiles:
    active: dev

mybatis:
  ###实体类位置
  type-aliases-package: top.testcross.zuji.bean
  #mapper.xml所在位置
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8020


pagehelper:
  # 数据库方言
  helper-dialect: mysql
  # 判断合理性比如负数和超过最大总数
  reasonable: true
  # 支持方法参数
  support-methods-arguments: true